### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by SteveEdson** [wseemann/FFmpegMediaPlayer#1]
Hey,

Not sure if I'm doing something wrong here but I'm getting an unsatisfied link error.

I've cloned the repo, extracted and copied the libs folder to my project, and included the FFMpegMediaPlayer project as well.

The only thing that I think could be causing this, is that my project-libraries setup is like this:

`FFMpegMediaPlayer -> My Base App -> Themed app that extends on the base app`.

I assume by including the libs folder, I don't need to run `ndk-build` in the folder right?

Cheers

**Comment by hafiz013** [comment]
hai, still i can participate. May I know why i try entering this url : 
"mms://livestream.iium.edu.my/iiumfm" it doesn't hear songs? second question may i know does FFmpegMediaPlayer support Mac instead of android?
