### ISSUE TITLE
using FFmpegMediaPlayer for video?

### ISSUE THREAD

**Issue by andreimarinescu** [wseemann/FFmpegMediaPlayer#10]
Would this work in conjuction with a SurfaceView for rendering Video files and streams, such as HLS? (I'm asking because it's a similar implementation to the native MediaPlayer that works this way).

What I'm looking for is a FFmpeg based library that I could use to replace MediaPlayer+SurfaceView.

Thanks!

**Comment by guhungry** [comment]
The setVideoSurface in JNI is commented out so i think it doesn't work on pre-compiled library

**Comment by AhmedWarreth** [comment]
Hi Guys,

Any luck getting this lib to render video on android using videoview? it plays my UDP stream audio. can't seem to get video working

**Comment by thailemon** [comment]
Same problem here. Plays audio without problem, but no video in my SurfaceView either, using setDisplay(holder)

**Comment by SohailZahidGit** [comment]
Video issue for both local and online streaming.

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
