### ISSUE TITLE
RTP audio stream in local network

### ISSUE THREAD

**Issue by westman2000** [wseemann/FFmpegMediaPlayer#101]
Hello.

I use your demo project  FMPDemo.apk to play RTP audio stream in local network from my server. Server send MP3 file to users

User get the URL in form: rtp: //192.168.112.255: 1111

There are several problems.
- A noticeable delay from the original 1-3 seconds.
- When you turn off the phone's screen starts lags.

**Comment by wseemann** [comment]
The delay is likely due to the audio being buffered before playback starts.
