### ISSUE TITLE
Support more API levels

### ISSUE THREAD

**Issue by mac-pro** [wseemann/FFmpegMediaPlayer#106]
Hi,

I think you absolutely know that min API level is 21. Would you please consider reviewing the code, to see if it can support more API levels?

Thank you,

**Comment by mr-cpp** [comment]
hi
i add to manifest this line under tag `<manifest>`:
` <uses-sdk tools:overrideLibrary="wseemann.media.ffmpegmediaplayer"/>`
all works fine

**Comment by mac-pro** [comment]
@mr-cpp 

Thanks, I know that flag. I also tested the library on API 10. However it's unclear whether the source can support lower API levels. Currently the source shows that it only supports API 21+.
