### ISSUE TITLE
not working with icecast-2.3.3 kh9

### ISSUE THREAD

**Issue by haemi** [wseemann/FFmpegMediaPlayer#110]
the player works perfect with servers like 2.3.2-kh30, but not 2.3.3-kh9.

Is there a workaround?

**Comment by tested0002** [comment]
Hi Haemi, I'm using this library on Icecast 2.4.0-kh2 and it works without any issue using the old library (below v1) and not the  v1.0.3 which is always crashing if you switch the stream more often

**Comment by wseemann** [comment]
The crash has nothing to to with the Icecast server version. There is already a bug report for the crash in question so I'm closing this issue.
