### ISSUE TITLE
Reduce Network Delay

### ISSUE THREAD

**Issue by azzahrah** [wseemann/FFmpegMediaPlayer#111]
I try play live streaming from wowza with rtmp protocol, when play using ffplay with --fflags nobuffer delay only 1,5 second, but play sing ffmpegmediaplayer delay is 20second,

howto reduce relay, mybe any parameter to passed? or special setting?

TIA

**Comment by ssfsimon** [comment]
+1 same question here. Is there an option to change the buffer size of the player?

**Comment by wseemann** [comment]
Yes there is, edit [ffmpeg_mediaplayer.h](https://github.com/wseemann/FFmpegMediaPlayer/blob/master/gradle/fmp-library/library/src/main/jni/player/ffmpeg_mediaplayer.h). Specifically, `MAX_AUDIOQ_SIZE` and `MAX_VIDEOQ_SIZE`. Then, recompile the library.
