### ISSUE TITLE
Is there any simple example using surface view?

### ISSUE THREAD

**Issue by johnconnorskynet** [wseemann/FFmpegMediaPlayer#112]
I tried to create a simple app that uses ffmpegplayer with a surface view with as an inspiration the FMPDemo VideoPlayerActivity class, i always get the same error print : 
E/FFmpegMediaPlayer: Error (0,0)
and nothing get displayed. I think the error from prepareAsync()
`
package belgaloo.test_cam;
import android.app.Activity;
import android.os.Bundle;
import android.net.Uri;
import android.util.Log;
import android.view.Surface;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.WindowManager;
import java.io.IOException;
import wseemann.media.FFmpegMediaPlayer;

public class MainActivity extends Activity{

```
private SurfaceView mmSurfaceView;
private SurfaceHolder mSurfaceHolder;
private Surface mFinalSurface;

private FFmpegMediaPlayer mMediaPlayer;

private FFmpegMediaPlayer.OnPreparedListener mOnPreparedListener = new FFmpegMediaPlayer.OnPreparedListener() {
    @Override
    public void onPrepared(FFmpegMediaPlayer mp) {

       mp.start();
    }
};

private FFmpegMediaPlayer.OnErrorListener mOnErrorListener = new FFmpegMediaPlayer.OnErrorListener() {
    @Override
    public boolean onError(FFmpegMediaPlayer mp, int what, int extra) {
        Log.d(MainActivity.class.getName(), "Error: " + what);
        return true;
    }
};

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);
    getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);

    String videoUrl ="https://ia800201.us.archive.org/22/items/ksnn_compilation_master_the_internet/ksnn_compilation_master_the_internet_512kb.mp4";
    Uri videoUri = Uri.parse(videoUrl);

    // set up the Surface video sink
    mmSurfaceView = (SurfaceView) findViewById(R.id.surfaceview);
    mSurfaceHolder = mmSurfaceView.getHolder();

    mSurfaceHolder.addCallback(new SurfaceHolder.Callback() {

        public void surfaceChanged(SurfaceHolder holder, int format, int width, int height) {
            Log.v("TAG", "surfaceChanged format=" + format + ", width=" + width + ", height="
                    + height);
        }

        public void surfaceCreated(SurfaceHolder holder) {
            mFinalSurface = holder.getSurface();               
            mMediaPlayer.setSurface(mFinalSurface);
        }

        public void surfaceDestroyed(SurfaceHolder holder) {
            Log.v("TAG", "surfaceDestroyed");
        }

    });

    mMediaPlayer = new FFmpegMediaPlayer();
    mMediaPlayer.setOnPreparedListener(mOnPreparedListener);
    mMediaPlayer.setOnErrorListener(mOnErrorListener);

    try {            
        mMediaPlayer.setDataSource(videoUrl);
        if (mFinalSurface != null) {
            mMediaPlayer.setSurface(mFinalSurface);
        }

    } catch (IOException ex) {
        ex.printStackTrace();
    }
    mMediaPlayer.prepareAsync();


}
```

}
`
`<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="belgaloo.test_cam.MainActivity">

<ImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:src="@drawable/background"/>

<SurfaceView
        android:id="@+id/surfaceview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

</RelativeLayout>`

Run LOG : 

> 10/24 15:18:35: Launching app
> $ adb shell am start -n "belgaloo.test_cam/belgaloo.test_cam.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
> Connected to process 306 on device htc-htc_one_m8-FA45DWM
> I/InstantRun: Instant Run Runtime started. Android package is belgaloo.test_cam, real application class is null.
> W/art: Failed to find OatDexFile for DexFile /data/data/belgaloo.test_cam/files/instant-run/dex/slice-slice_3-classes.dex ( canonical path /data/data/belgaloo.test_cam/files/instant-run/dex/slice-slice_3-classes.dex) with checksum 0xfc6a9721 in OatFile /data/data/belgaloo.test_cam/cache/slice-slice_3-classes.dex
> V/FFmpegMediaPlayer-JNI: native_init
> V/FFmpegMediaPlayer-JNI: native_setup
> V/FFmpegMediaPlayer-JNI: setDataSource: path https://ia800201.us.archive.org/22/items/ksnn_compilation_master_the_internet/ksnn_compilation_master_the_internet_512kb.mp4
> V/FFmpegMediaPlayer-JNI: notify: 100
> D/Atlas: Validating map...
> E/FFmpegMediaPlayer: Error (0,0)
> D/belgaloo.test_cam.MainActivity: Error: 0
> I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030_msm8974_refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030__release_AU ()
>               OpenGL ES Shader Compiler Version: E031.25.03.00
>               Build Date: 12/11/14 Thu
>               Local Branch: 
>               Remote Branch: refs/tags/AU_LINUX_ANDROID_LA.BF.1.1_RB1.05.00.00.002.030
>               Local Patches: NONE
>               Reconstruct Branch: NOTHING
> V/TAG: surfaceChanged format=4, width=1080, height=1776

What i am trying to achieve ultimately is to overlay a surface view playing a video with an alpha channel on top of a camera preview.

Thanx.

**Comment by wseemann** [comment]
The problem isn't with the fact that you are trying to use a `SurfaceView`. Your URL protocol is `https`, which is currently unsupported.
