### ISSUE TITLE
I am not able to play .ts and .mkv format for live tv stream using this library.

### ISSUE THREAD

**Issue by yuvaraj119** [wseemann/FFmpegMediaPlayer#129]
Live Stream URL: http://matrixip.dyndns.org:8080/movie/master-hxH3pPkFKz-10107469/7675455575545/6426.mkv, http://matrixip.dyndns.org:8080/live/master-hxH3pPkFKz-10107469/7675455575545/6031.ts
it throws Error (0, 0) for both.

**Comment by Eido95** [comment]
I tried to play both files you provided using my desktop media player, but it seems that they are unavailable or don't  streamed by the hosting serve. 
Can you view those files by inserting those URL's to regular media player (for example, VLC)?

**Comment by yuvaraj119** [comment]
@Eido95 yes it was server error thanks for your support.
