### ISSUE TITLE
Fatal Error on Android L devices

### ISSUE THREAD

**Issue by SteveEdson** [wseemann/FFmpegMediaPlayer#13]
I'm using an old version of this library, (the sourceforge version). My app has many flavours, and each flavour has a different package name. I originally added the following workaround to the library, so that it used the appropriate directory to load the system files.

```java
static {
    String libPath = Streamer.nativeDir;		       
    Log.w(TAG, "Native dir is " + libPath);		      
    for (int i = 0; i < JNI_LIBRARIES.length; i++) {	                  
        System.load(libPath + JNI_LIBRARIES[i]);	      
    }	      	        
    native_init();	        
    bind_variables(mAudioFrameBuffer, mAudioFrameBufferDataLength);	    
} 
```

```java
PackageManager m = this.getPackageManager();
String s = this.getPackageName();
try {
    PackageInfo p = m.getPackageInfo(s, 0);
    s = p.applicationInfo.dataDir;
} catch (PackageManager.NameNotFoundException e) {
    Log.w(TAG, "Error Package name not found ", e);
}

nativeDir = s + "/lib/";

...
// Init the FFmpeg library later on
```

However, this is no longer working due to changes in the library.

Is it possible to get this working again? Or make it less of a hack, e.g. passing in the appropriate parameters when constructing the FFMpeg object? Either the path to load, a PackageInfo object, or a Context object?

Gradle is now the recommended build system, so this might be a more common scenario in the future.

Thanks again,

Steve

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
