### ISSUE TITLE
Demo app doesn't work

### ISSUE THREAD

**Issue by FivesoftCode** [wseemann/FFmpegMediaPlayer#158]
Demo app always displays black screen. Tried with different urls.
Library also doesn't work. Always calls on error listener with params: what = 0, extra = 0.

**Comment by wseemannroku** [comment]
Can you provide sample URLs to test with?

**Comment by wseemann** [comment]
Can you provide the URLs you tested with?

**Comment by wseemann** [comment]
Closed due to inactivity.
