### ISSUE TITLE
isPlaying() returns TRUE even if it was not started

### ISSUE THREAD

**Issue by ssuukk** [wseemann/FFmpegMediaPlayer#17]
1) prepare media player as normal, set source, set listeners etc., do not mediaPlayer.start() it.

2) do mediaPlayer.isPlaying() - returns true! (that confuses my player a bit!)

3) as soon as you start() the player, isPlaying() works as expected (says "false" when not playing and "true" when playing)

**Comment by ssuukk** [comment]
HI,

I was trying to flattr you today, but when I click green "flattr" button on
the page you gave me I am forwarded to an empty page:

https://api.flattr.com/button/click/8679d8db5ffcd8c7634895a09f188371

Can you check if it is the same on your browser?

Regards,

ssuukk

2014-10-16 22:04 GMT+02:00 William Seemann <notifications@github.com>:

> Thank you for the kind comments. I initially created this player for my
> own application ServeStream:
>
>
> https://play.google.com/store/apps/details?id=net.sourceforge.servestream&hl=en
>
> I figured it would be useful to others and I didn't want them to struggle
> making players on their own so I open sourced it. I work full time as a
> Software Engineer, but I do this for "fun", ha. I still have several
> enhacements to make, including video playback. You can also use Flattr to
> donate:
> https://flattr.com/thing/2667714/wseemannFFmpegMediaMetadataRetriever-on-GitHub
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wseemann/FFmpegMediaPlayer/issues/17#issuecomment-59421610>
> .
>



-- 

*XenoAmp* - a media player with a difference • Demo on [image: YouTube]
YouTube <http://www.youtube.com/watch?v=9O0xvDLw8Ek> • Get it ftom Google
Play <https://play.google.com/store/apps/details?id=pl.qus.xenoamp> • Folow
it on Twitter <https://twitter.com/XenoAmpMusic> • Report bugs to XDA Thread
<http://forum.xda-developers.com/showthread.php?t=1822492>

[image: XenoBanner]

**Comment by wseemann** [comment]
Hello, please use this link: http://flattr.com/thing/2667714/wseemannFFmpegMediaMetadataRetriever-on-GitHub.
