### ISSUE TITLE
Fatal Signal 11 (SIGSEGV) 

### ISSUE THREAD

**Issue by DrDreave** [wseemann/FFmpegMediaPlayer#19]
Hi it's me again.

We're facing the next problem using your player. In undefined intervals a native error occurs and causes a crash of our app.

Log-Entry: 
10-22 16:03:24 474: A/libc(3165): Fatal signal 11 (SIGSEGV) at 0x3c81e736 (code=1), thread 3726 (AsyncTask #4)

It appears mostly when starting and stopping a stream very often in a row, but also on a single start.
Is this a known issue? Is there anything we can do about it?

Any help would be appreciated.

Greetz David.

**Comment by radzio** [comment]
I'm still facing similar issue: https://github.com/wseemann/FFmpegMediaPlayer/issues/29 :(

**Comment by astinx** [comment]
Me too https://github.com/wseemann/FFmpegMediaPlayer/issues/29, there's some version that we could checkout to ensure that this is fixed?
