### ISSUE TITLE
After I used proguard to obfuscate, an error occurred when I launcher the APP.

### ISSUE THREAD

**Issue by yuchin067** [wseemann/FFmpegMediaPlayer#26]
I use the proguard to obfuscate my project and install the apk.
When I launcher the APP, an error occurs.

Error message as follows:
12-22 14:22:34.821: E/FFmpegMediaPlayer-JNI(19497): RegisterNatives failed for 'wseemann/media/FFmpegMediaPlayer'
12-22 14:22:34.821: E/FFmpegMediaPlayer-JNI(19497): ERROR: FFmpegMediaPlayer native registration failed
12-22 14:22:34.821: D/AndroidRuntime(19497): Shutting down VM
12-22 14:22:34.822: E/AndroidRuntime(19497): FATAL EXCEPTION: main
12-22 14:22:34.822: E/AndroidRuntime(19497): Process: com.zyxel.zCloud, PID: 19497
12-22 14:22:34.822: E/AndroidRuntime(19497): java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.zyxel.zCloud-2/lib/arm/libffmpeg_mediaplayer_jni.so"

I tried to add parameter in proguard-project.txt as follows:
-libraryjars /libs/fmp.jar
-keep class wseemann.media.FFmpegMediaPlayer **. {*;}

But it still can not work and the error message is the same.
How can I to fix this problem? 
Thanks.

**Comment by wseemann** [comment]
Thanks for providing the solution to your problem.
