### ISSUE TITLE
Is getMetadata working?

### ISSUE THREAD

**Issue by radzio** [wseemann/FFmpegMediaPlayer#27]
Hi,

Thanks for great lib. I have only one problem. getMedata method is not returning anything more than "audiocodec" and "duration". I am using this:

    wseemann.media.Metadata metadata = fFmpegMediaPlayer.getMetadata(false, false);

for this stream: http://pub8.rockradio.com:80/rr_indierock

Any chances / ideas how to get album/artist info? Currently I am using custom Icy parser written in Java but I wanted to switch to getMatada method from your lib...

Cheers,
Radek

**Comment by wseemann** [comment]
I modified the `getMetadata` function to return shoutcast metadata.
