### ISSUE TITLE
Differences between FMP and FMMR projects?

### ISSUE THREAD

**Issue by rfoa** [wseemann/FFmpegMediaPlayer#28]
What are the differences between your two projects?
Both use the same codecs and FFmpeg build?
Both take the same metadata?

Thanks!

**Comment by wseemann** [comment]
FFmpegMediaMetadataRetriever provides a unified interface for retrieving frame and meta data from an input media file. FFmpegMediaPlayer provides a unified interface for playing audio files and streams.

**Comment by rfoa** [comment]
Ok. Thanks

**Comment by permenko** [comment]
how to use poth of them, i have 
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_75\bin\java.exe'' finished with non-zero exit value 2
