### ISSUE TITLE
Start called in state 4

### ISSUE THREAD

**Issue by nkuznetsow** [wseemann/FFmpegMediaPlayer#33]
I can not start playing! I get next error: "Start called in state 4".

I use to start playing next code:

FFmpegMediaPlayer mp = FFmpegMediaPlayer.create(getApplicationContext(), Uri.parse(url));
mp.start(); // player must be already prepared here!

I get next messages in console:

02-21 01:42:21.758: V/FFmpegMediaPlayer-JNI(6466): native_setup
02-21 01:42:21.758: V/FFmpegMediaPlayer(6466): constructor
02-21 01:42:21.758: V/FFmpegMediaPlayer(6466): setListener
02-21 01:42:21.758: D/FFmpegMediaPlayer(6466): Couldn't open file on client side, trying server side
02-21 01:42:21.759: V/FFmpegMediaPlayer-JNI(6466): setDataSource: path http://cfm.jazzandclassic.ru:14534/rcstream.mp3
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): setDataSource(http://cfm.jazzandclassic.ru:14534/rcstream.mp3)
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): prepare
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): MediaPlayer::setAudioStreamType
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): prepare complete - status=0
02-21 01:42:21.759: V/FFmpegMediaPlayer-JNI(6466): setAudioStreamType: 3
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): MediaPlayer::setAudioStreamType
02-21 01:42:21.759: V/FFmpegMediaPlayer-JNI(6466): start
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): start
02-21 01:42:21.759: E/FFmpegMediaPlayer(6466): start called in state 4
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): message received msg=100, ext1=-38, ext2=0
02-21 01:42:21.759: E/FFmpegMediaPlayer(6466): error (-38, 0)
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): callback application
02-21 01:42:21.759: V/FFmpegMediaPlayer-JNI(6466): notify: 100
02-21 01:42:21.759: V/FFmpegMediaPlayer(6466): back from callback
02-21 01:42:21.776: E/FFmpegMediaPlayer(6466): Error (-38,0)
02-21 01:42:21.801: V/FFmpegMediaPlayer-JNI(6466): native_finalize
02-21 01:42:21.801: V/FFmpegMediaPlayer-JNI(6466): release
02-21 01:42:21.808: V/FFmpegMediaPlayer-JNI(6466): native_finalize
02-21 01:42:21.808: V/FFmpegMediaPlayer-JNI(6466): release
02-21 01:42:23.934: V/FFmpegMediaPlayer(6466): initAudioTrack(44100, 2, 1)
02-21 01:42:23.936: I/FFmpegMediaPlayer(6466): Minimum buffer size set to: 28224
02-21 01:42:23.942: E/TAG(6466): Fill buffer: 4608 -> 28224
02-21 01:42:23.944: E/TAG(6466): Fill buffer: 4608 -> 28224
02-21 01:42:23.945: E/TAG(6466): Fill buffer: 4608 -> 28224
02-21 01:42:23.949: E/TAG(6466): Fill buffer: 4608 -> 28224
02-21 01:42:23.951: E/TAG(6466): Fill buffer: 4608 -> 28224
02-21 01:42:23.952: E/TAG(6466): Fill buffer: 4608 -> 28224
02-21 01:42:23.953: E/TAG(6466): Fill buffer: 4608 -> 28224
02-21 01:42:23.953: V/FFmpegMediaPlayer(6466): message received msg=1, ext1=0, ext2=0
02-21 01:42:23.953: V/FFmpegMediaPlayer(6466): prepared
02-21 01:42:23.953: V/FFmpegMediaPlayer(6466): callback application
02-21 01:42:23.953: V/FFmpegMediaPlayer-JNI(6466): notify: 1
02-21 01:42:23.954: V/FFmpegMediaPlayer(6466): back from callback

I have tried to start player another way:

FFmpegMediaPlayer mp = new FFmpegMediaPlayer();
mp.setDataSource(getApplicationContext(), Uri.parse(url));
mp.prepare();
mp.start();

The same result!

Android 5.0.1, Nexus 5. I have used prebuild libs, and libs builded from last version of source code.

**Comment by upelsin** [comment]
Same for me here, except that "start called in state 0".

```
 V/FFmpegMediaPlayer-JNI﹕ setDataSource: path http://cs4271.vk.me/u1671935/audios/444359f53776.mp3?extra=SD_PD0U4EMcNfxN82irKO4L2DD4EwpGwKS3nenxV-1hDt9SfLnAbhJbHoJSWyhpYtLxey3Z5W_LlB5OBzzlLcNm7kpM77w
 V/FFmpegMediaPlayer﹕ setDataSource(http://cs4271.vk.me/u1671935/audios/444359f53776.mp3?extra=SD_PD0U4EMcNfxN82irKO4L2DD4EwpGwKS3nenxV-1hDt9SfLnAbhJbHoJSWyhpYtLxey3Z5W_LlB5OBzzlLcNm7kpM77w)
 V/FFmpegMediaPlayer﹕ prepare
 V/FFmpegMediaPlayer﹕ MediaPlayer::setAudioStreamType
 V/FFmpegMediaPlayer﹕ prepare complete - status=0
 V/FFmpegMediaPlayer-JNI﹕ setVolume: left 1.000000  right 1.000000
 V/FFmpegMediaPlayer﹕ MediaPlayer::setVolume(1.000000, 1.000000)
 V/FFmpegMediaPlayer﹕ message received msg=100, ext1=-3, ext2=0
 E/FFmpegMediaPlayer﹕ error (-3, 0)
 V/FFmpegMediaPlayer﹕ callback application
 V/FFmpegMediaPlayer-JNI﹕ notify: 100
 V/FFmpegMediaPlayer﹕ back from callback
 V/FFmpegMediaPlayer-JNI﹕ start
 V/FFmpegMediaPlayer﹕ start
 E/FFmpegMediaPlayer﹕ Error (-3,0)
 E/FFmpegMediaPlayer﹕ start called in state 0
 V/FFmpegMediaPlayer﹕ message received msg=100, ext1=-38, ext2=0
 E/FFmpegMediaPlayer﹕ error (-38, 0)
 V/FFmpegMediaPlayer﹕ callback application
 V/FFmpegMediaPlayer-JNI﹕ notify: 100
 V/FFmpegMediaPlayer﹕ back from callback
 E/FFmpegMediaPlayer﹕ Error (-38,0)
 V/FFmpegMediaPlayer﹕ initAudioTrack(44100, 2, 1)
 I/FFmpegMediaPlayer﹕ Minimum buffer size set to: 28224
 E/TAG﹕ Fill buffer: 4608 -> 28224
 E/TAG﹕ Fill buffer: 4608 -> 28224
 E/TAG﹕ Fill buffer: 4608 -> 28224
 E/TAG﹕ Fill buffer: 4608 -> 28224
 E/TAG﹕ Fill buffer: 4608 -> 28224
 E/TAG﹕ Fill buffer: 4608 -> 28224
 E/TAG﹕ Fill buffer: 4608 -> 28224
 V/FFmpegMediaPlayer﹕ message received msg=1, ext1=0, ext2=0
 V/FFmpegMediaPlayer﹕ prepared
 V/FFmpegMediaPlayer﹕ callback application
 V/FFmpegMediaPlayer-JNI﹕ notify: 1
 V/FFmpegMediaPlayer﹕ back from callback
```

@wseemann, any Ideas?

**Comment by jmbrenna** [comment]
I have something similar but I was curious if anyone knew what Error (-3,0) meant?

**Comment by surveshoeb** [comment]
`02-26 17:00:53.670 29215-29215/in.adevole.amplify E/FFmpegMediaPlayer: Error (-38,0)`

Reason of Error?
