### ISSUE TITLE
setOnBufferingUpdateListener never called

### ISSUE THREAD

**Issue by MrVilkaman** [wseemann/FFmpegMediaPlayer#40]
I use example code form "Usage" section in main page.

I added next code:
```
 mp.setOnBufferingUpdateListener(new FFmpegMediaPlayer.OnBufferingUpdateListener() {
                @Override
                public void onBufferingUpdate(FFmpegMediaPlayer fFmpegMediaPlayer, int i) {
                    Log.v("TAG", "onBufferingUpdate " + i);
                }
            });
```
But onBufferingUpdate never shown in log.

I use http stream
So, What could be the problem?

Thanks

**Comment by satyres** [comment]
I have the same issue please fix it !

**Comment by adelinolobao** [comment]
Hi guys,

Quick question, do you guys manage to fix this issue? I also have this problem when using the setOnInfoListener. 

So both setOnBufferingUpdateListener and setOnInfoListener are never triggered. I also debug internal implementation from FFmpegMediaPlayer and it looks like the only postEventFromNative triggered and the 1 (related with onPreparedListener) and the errorListener.

If the developer is not working actively in the project please mark it as archived in README.txt so people now that is not maintained anymore.

**Comment by adelinolobao** [comment]
Just a quick update, looking to the C++ implementation it looks like the setOnBufferingUpdateListener and setOnInfoListener are not implemented.

https://github.com/wseemann/FFmpegMediaPlayer/blob/master/gradle/fmp-library/library/src/main/jni/player/mediaplayer.cpp

go to line 649 to 653 (you will see that the code is commented for setOnInfoListener)

go to line 666 to 668 (you will see that we don't have implementation for setOnBufferingUpdateListener)

So if you are planning to use these two methods forget it :P

**Comment by wseemann** [comment]
This method is now available in the rewritten version of the library.
