### ISSUE TITLE
Gradle & Maven Support

### ISSUE THREAD

**Issue by AOrobator** [wseemann/FFmpegMediaPlayer#41]
Please add support for building with Gradle and using maven

**Comment by wseemann** [comment]
Done.

**Comment by AOrobator** [comment]
The Readme should also be updated to show how to use it in build.gradle file.

**Comment by wseemann** [comment]
Then submit a pull request with the updated README.

**Comment by AOrobator** [comment]
I just tried to add it my gradle file using

    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.0'

but I got the following error:

Error:Dependency com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.0 on project app resolves to an APK archive which is not supported as a compilation dependency. File: /Users/AndrewOrobator/.gradle/caches/modules-2/files-2.1/com.github.wseemann/FFmpegMediaMetadataRetriever/1.0.0/6425843abea10b64bc89f33b1ff4b52c0bb5152a/FFmpegMediaMetadataRetriever-1.0.0.apk
