### ISSUE TITLE
MMS stream that is not playable

### ISSUE THREAD

**Issue by ssuukk** [wseemann/FFmpegMediaPlayer#44]
My user found a MMS stream that plays elswhere, but not on ffmpegmediaplayer:

mms://195.23.102.196/m80cbr96

Output looks like this:

03-21 14:27:12.470: E/TAG(28043): avcodec_decode_audio4() decoded no frame
03-21 14:27:12.470: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:12.470: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:13.560: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:13.560: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:13.570: E/TAG(28043): avcodec_decode_audio4() decoded no frame
03-21 14:27:13.570: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:14.680: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:14.680: E/TAG(28043): avcodec_decode_audio4() decoded no frame
03-21 14:27:14.680: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:14.690: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:15.790: E/TAG(28043): avcodec_decode_audio4() decoded no frame
03-21 14:27:15.790: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:15.790: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:15.800: E/TAG(28043): avcodec_decode_audio4() decoded no frame
03-21 14:27:15.800: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:16.900: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:16.910: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:16.910: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:18.020: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:18.020: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:18.030: E/TAG(28043): avcodec_decode_audio4() decoded no frame
03-21 14:27:18.030: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:19.140: E/TAG(28043): Fill buffer: 0 -> 112896
03-21 14:27:19.150: E/TAG(28043): avcodec_decode_audio4() decoded no frame

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
