### ISSUE TITLE
Continue buffering after pausing the player.

### ISSUE THREAD

**Issue by ashokkumar88** [wseemann/FFmpegMediaPlayer#46]
Buffering is stops after pausing the player. Is it possible to continue the buffering after pausing the player?

**Comment by Harpreet4u** [comment]
Buffering stops as your buffer specified in FFMpegMediaPlayer.java class overflows. You can increase it's size and it will continue buffering.

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
