### ISSUE TITLE
I have 'Fatal signal 11' Error.

### ISSUE THREAD

**Issue by zzilssun** [wseemann/FFmpegMediaPlayer#49]
I  faced a problem with your FFmpegMediaPlayer.

I was checked crash log. And I found that 'ffmpeg_mediaplayer.c' is a problem.

Perhaps it seems to be in trouble a null reference.

I send log to you.

------------------------------------------------------------------------------------------------------------------------

04-17 11:47:11.465      891-891/? D/CrashAnrDetector﹕ Build: samsung/ks01lteskt/ks01lteskt:4.4.2/KOT49H/E330SKSUCNJ1:user/release-keys
    Hardware: MSM8974
    Revision: 13
    Bootloader: E330SKSUCNJ1
    Radio: unknown
    Kernel: Linux version 3.4.0-2933244 (dpi@SWDD5612) (gcc version 4.7 (GCC) ) #1 SMP PREEMPT Mon Oct 6 08:29:22 KST 2014
    *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Build fingerprint: 'samsung/ks01lteskt/ks01lteskt:4.4.2/KOT49H/E330SKSUCNJ1:user/release-keys'
    Revision: '13'
    pid: 27251, tid: 27460, name: oster.radiotest  >>> com.apposter.radiotest <<<
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
    r0 00000000  r1 00000064  r2 00000001  r3 00000000
    r4 7c4cafe0  r5 00000000  r6 00000001  r7 7b3b8a48
    r8 7c4cb038  r9 7c4cbc50  sl beaf22e4  fp 400af2ec
    ip 6b444001  sp 78576d00  lr 7846f1d7  pc 00000000  cpsr 000f0010
    d0  656d2f2f3a706374  d1  6576726573616964
    d2  74656e746e692e72  d3  3f3435353a756d2e
    d4  bff0000000000000  d5  bff0000000000000
    d6  3ff0000000000000  d7  bff0000000000000
    d8  0000000000000000  d9  0000000000000000
    d10 0000000000000000  d11 0000000000000000
    d12 0000000000000000  d13 0000000000000000
    d14 0000000000000000  d15 0000000000000000
    d16 6966207475706e49  d17 646c756f6320656c
    d18 6964656d2f2f3a70  d19 2e72657672657361
    d20 6d2e74656e746e69  d21 69743f3435353a75
    d22 20303d74756f656d  d23 203a64656c696166
    d24 000e000d000c000b  d25 0010000f000d000e
    d26 0000000000000000  d27 0000000000000000
    d28 001e001d001c001b  d29 0020001f001d001e
    d30 0010001000100010  d31 0000000000000000
    scr 60000012
    backtrace:
    #00  pc 00000000  <unknown>
    #01  pc 000071d5  /data/app-lib/com.apposter.radiotest-9/libffmpeg_mediaplayer_jni.so (player_prepare+420)
    #02  pc 0000d290  /system/lib/libc.so (__thread_entry+72)
    #03  pc 0000d428  /system/lib/libc.so (pthread_create+240)
    stack:
    78576cc0  400ad1d8  /system/lib/libc.so
    78576cc4  400bb334
    78576cc8  0000000a
    78576ccc  400782ad  /system/lib/libc.so (puts+92)
    78576cd0  7c4cb038
    78576cd4  78576ce0  [stack:27460]
    78576cd8  00000002
    78576cdc  00000000
    78576ce0  784729d5  /data/app-lib/com.apposter.radiotest-9/libffmpeg_mediaplayer_jni.so
    78576ce4  0000001e
    78576ce8  400a4398  /system/lib/libc.so
    78576cec  00000001
    78576cf0  7c4cafe0
    78576cf4  ffffff92
    78576cf8  00000001
    78576cfc  7846f0eb  /data/app-lib/com.apposter.radiotest-9/libffmpeg_mediaplayer_jni.so (player_prepare+186)
    #00  78576d00  00000001
    ........  ........
    #01  78576d00  00000001
    78576d04  00000000
    78576d08  00000000
    78576d0c  400b1394
    78576d10  7b794910
    78576d14  00000000
    78576d18  00000000
    78576d1c  00000000
    78576d20  00000000
    78576d24  00000000
    78576d28  00000000
    78576d2c  00000000
    78576d30  00000000
    78576d34  00000000
    78576d38  00000000
    78576d3c  00000000
    ........  ........
    #02  78576db8  7b3b8a48
    78576dbc  7998f808
    78576dc0  78576dd0  [stack:27460]
    78576dc4  00000002
    78576dc8  00000078
    78576dcc  4007042c  /system/lib/libc.so (pthread_create+244)
    #03  78576dd0  78576dd0  [stack:27460]
    78576dd4  7998f808
    78576dd8  00000073
    78576ddc  00000000
    78576de0  00000000
    78576de4  f6b4522c
    78576de8  00000000
    78576dec  00000000
    78576df0  00000000
    78576df4  00000000
    78576df8  00000000
    78576dfc  00000000
    78576e00  00000000
    78576e04  00000000
    78576e08  00000000
    78576e0c  00000000
    memory near r4:
    7c4cafc0 00000000 00000000 00000000 00000000
    7c4cafd0 00000000 00000000 00000000 00000c8b
    7c4cafe0 00000000 ffffffff ffffffff 00000000

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
