### ISSUE TITLE
buildNative fails on "libavcodec/avcodec.h: No such file or directory"

### ISSUE THREAD

**Issue by idanya** [wseemann/FFmpegMediaPlayer#54]
when running buildNative, ffmpeg compiles alright but when trying to compile ffmpeg_mediaplayer it fails with the following error:

ffmpeg_mediaplayer.h:22:32: fatal error: libavcodec/avcodec.h: No such file or directory

NDK path to includes is: 
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/../ffmpeg/ffmpeg/$(TARGET_ARCH_ABI)/include
and the libraries are there for all arch's..

**Comment by wseemann** [comment]
This issue was fixed in the library rewrite.
