### ISSUE TITLE
Cannot play local video file on Andriod tablet

### ISSUE THREAD

**Issue by shalinashiyan** [wseemann/FFmpegMediaPlayer#55]
Hi, 
First all, I have to say, this FFmpegMediaPlayer is great. I have been looking for examples like this for quite some time. I will definitely show my appreciation ...

One question though. I followed your instruction (using the prebuilt libraries in eclipse). Did a clean build and then downloaded the build to an andriod tablet. 
Android SDK: 5.0.1
Tablet HW:     Samsung SM-T210R
Android version: 4.4.2

However, I got "error (1, 0)" below.

Log like this: 
06-10 10:52:02.234: D/GC(12204): <tid=12204> OES20 ===> GC Version   : GC Ver rls_pxa988_KK44_GC13.20 
06-10 10:52:02.404: D/OpenGLRenderer(12204): Enabling debug mode 0
06-10 10:52:02.444: D/dalvikvm(12204): Trying to load lib /data/app-lib/com.example.ffmpegandroidplayer-11/libavutil.so 0x41e1bcb8
06-10 10:52:02.444: D/dalvikvm(12204): Added shared lib /data/app-lib/com.example.ffmpegandroidplayer-11/libavutil.so 0x41e1bcb8
06-10 10:52:02.444: D/dalvikvm(12204): No JNI_OnLoad found in /data/app-lib/com.example.ffmpegandroidplayer-11/libavutil.so 0x41e1bcb8, skipping init
06-10 10:52:02.444: D/dalvikvm(12204): Trying to load lib /data/app-lib/com.example.ffmpegandroidplayer-11/libavcodec.so 0x41e1bcb8
06-10 10:52:02.444: W/linker(12204): libavcodec.so has text relocations. This is wasting memory and is a security risk. Please fix.
06-10 10:52:02.444: D/dalvikvm(12204): Added shared lib /data/app-lib/com.example.ffmpegandroidplayer-11/libavcodec.so 0x41e1bcb8
06-10 10:52:02.444: D/dalvikvm(12204): No JNI_OnLoad found in /data/app-lib/com.example.ffmpegandroidplayer-11/libavcodec.so 0x41e1bcb8, skipping init
06-10 10:52:02.444: D/dalvikvm(12204): Trying to load lib /data/app-lib/com.example.ffmpegandroidplayer-11/libavformat.so 0x41e1bcb8
06-10 10:52:02.454: D/dalvikvm(12204): Added shared lib /data/app-lib/com.example.ffmpegandroidplayer-11/libavformat.so 0x41e1bcb8
06-10 10:52:02.454: D/dalvikvm(12204): No JNI_OnLoad found in /data/app-lib/com.example.ffmpegandroidplayer-11/libavformat.so 0x41e1bcb8, skipping init
06-10 10:52:02.454: D/dalvikvm(12204): Trying to load lib /data/app-lib/com.example.ffmpegandroidplayer-11/libswresample.so 0x41e1bcb8
06-10 10:52:02.454: D/dalvikvm(12204): Added shared lib /data/app-lib/com.example.ffmpegandroidplayer-11/libswresample.so 0x41e1bcb8
06-10 10:52:02.454: D/dalvikvm(12204): No JNI_OnLoad found in /data/app-lib/com.example.ffmpegandroidplayer-11/libswresample.so 0x41e1bcb8, skipping init
06-10 10:52:02.454: D/dalvikvm(12204): Trying to load lib /data/app-lib/com.example.ffmpegandroidplayer-11/libffmpeg_mediaplayer_jni.so 0x41e1bcb8
06-10 10:52:02.464: D/dalvikvm(12204): Added shared lib /data/app-lib/com.example.ffmpegandroidplayer-11/libffmpeg_mediaplayer_jni.so 0x41e1bcb8
06-10 10:52:02.464: V/FFmpegMediaPlayer-JNI(12204): native_init
06-10 10:52:02.474: V/FFmpegMediaPlayer-JNI(12204): native_setup
06-10 10:52:02.474: V/FFmpegMediaPlayer(12204): constructor
06-10 10:52:02.474: V/FFmpegMediaPlayer(12204): setListener
06-10 10:52:02.474: V/FFmpegMediaPlayer-JNI(12204): setDataSourceFD: fd 50
06-10 10:52:02.474: V/FFmpegMediaPlayer(12204): setDataSource(50, 190977, 15424230)
06-10 10:52:02.474: V/FFmpegMediaPlayer(12204): prepareAsync
06-10 10:52:02.474: V/FFmpegMediaPlayer(12204): MediaPlayer::setAudioStreamType
06-10 10:52:02.984: V/FFmpegMediaPlayer(12204): message received msg=100, ext1=1, ext2=0
06-10 10:52:02.984: E/FFmpegMediaPlayer(12204): error (1, 0)
06-10 10:52:02.984: V/FFmpegMediaPlayer(12204): callback application
06-10 10:52:02.984: V/FFmpegMediaPlayer-JNI(12204): notify: 100
06-10 10:52:02.984: V/FFmpegMediaPlayer(12204): back from callback
06-10 10:52:02.984: E/FFmpegMediaPlayer(12204): Error (1,0)
06-10 10:52:02.984: V/FFmpegMediaPlayer-JNI(12204): release
06-10 10:52:02.984: V/FFmpegMediaPlayer(12204): setListener
06-10 10:52:02.984: V/FFmpegMediaPlayer(12204): disconnect
06-10 10:52:02.984: V/FFmpegMediaPlayer(12204): destructor
06-10 10:52:02.984: V/FFmpegMediaPlayer(12204): disconnect
06-10 10:52:47.398: V/FFmpegMediaPlayer-JNI(12204): release

My java code looks like this.
---------------------------------------------------------------
package com.example.ffmpegandroidplayer;

import android.os.Bundle;

import java.io.IOException;
import android.app.Activity;

import wseemann.media.FFmpegMediaPlayer;
import wseemann.media.FFmpegMediaPlayer.OnPreparedListener;
import wseemann.media.FFmpegMediaPlayer.OnVideoSizeChangedListener;

/*
import android.media.MediaPlayer;
import android.media.MediaPlayer.OnPreparedListener;
import android.media.MediaPlayer.OnVideoSizeChangedListener;
*/
import android.net.Uri;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.os.Handler;

public class FFmpegAndroidPlayer extends Activity implements SurfaceHolder.Callback, OnPreparedListener,
OnVideoSizeChangedListener{

	
	private FFmpegMediaPlayer mediaPlayer;
//	private MediaPlayer mediaPlayer;
	
	private SurfaceHolder vidHolder;
	private SurfaceView vidSurface;
	
	private static Handler handler = new Handler();
	
	
	@Override
	public void onCreate(Bundle icicle) {	
			super.onCreate(icicle);
			
			setContentView(R.layout.activity_main);
			
			vidSurface = (SurfaceView) findViewById(R.id.surfaceview);
			vidHolder = vidSurface.getHolder();
			vidHolder.addCallback(this);
			vidHolder.setType(SurfaceHolder.SURFACE_TYPE_PUSH_BUFFERS);	
	}

	private void playVideo(){
		try {

			mediaPlayer = new FFmpegMediaPlayer();
//			mediaPlayer = new MediaPlayer();
                   	
			mediaPlayer.setDataSource(this, Uri.parse("android.resource://" + getPackageName() + "/" + R.raw.out));
			mediaPlayer.setDisplay(vidHolder);
			
			mediaPlayer.prepareAsync();
			//mediaPlayer.prepare();
			mediaPlayer.setOnPreparedListener(this);
			
			mediaPlayer.setOnErrorListener(new FFmpegMediaPlayer.OnErrorListener() {

			    @Override
			    public boolean onError(FFmpegMediaPlayer mp, int what, int extra) {
			        mp.release();
			        return false;
			    }
			});
			

			// TODO Auto-generated catch block
		} catch (IllegalArgumentException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IllegalStateException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Override
	public void onVideoSizeChanged(FFmpegMediaPlayer arg0, int arg1, int arg2) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onPrepared(FFmpegMediaPlayer mp) {
		// TODO Auto-generated method stub
		
		mediaPlayer.start();
		
	}

	@Override
	public void surfaceChanged(SurfaceHolder arg0, int arg1, int arg2, int arg3) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void surfaceCreated(SurfaceHolder arg0) {
		// TODO Auto-generated method stub
		playVideo();
		
	}

	@Override
	public void surfaceDestroyed(SurfaceHolder arg0) {
		// TODO Auto-generated method stub
		if (mediaPlayer != null) {
			mediaPlayer.release();
			mediaPlayer = null;
		}
	}
}

Please note that if I use the Andriod media player (i.e. rename the above FFmpegMediaPlayer to MediaPlayer), the media player works fine (I am able to play a video file).

**Comment by reyalpsirc** [comment]
I'm also facing the same issue with the pre built libraries but with an audio RTMP instead.
The thing is that if I try the same code on a Genymotion emulator, then it works.

My log file:

	06-23 20:40:20.206    2256-2256/com.example.testrtmp D/dalvikvm﹕ GC_FOR_ALLOC freed 43K, 9% free 9282K/10143K, paused 44ms
	06-23 20:40:20.216    2256-2256/com.example.testrtmp I/dalvikvm-heap﹕ Grow heap (frag case) to 10.695MB for 1639696-byte allocation
	06-23 20:40:20.256    2256-2267/com.example.testrtmp D/dalvikvm﹕ GC_FOR_ALLOC freed 3K, 8% free 10880K/11811K, paused 20ms
	06-23 20:40:20.376    2256-2256/com.example.testrtmp D/dalvikvm﹕ Trying to load lib /data/data/com.example.testrtmp/lib/libavutil.so 0x41397cb0
	06-23 20:40:20.416    2256-2256/com.example.testrtmp D/dalvikvm﹕ Added shared lib /data/data/com.example.testrtmp/lib/libavutil.so 0x41397cb0
	06-23 20:40:20.416    2256-2256/com.example.testrtmp D/dalvikvm﹕ No JNI_OnLoad found in /data/data/com.example.testrtmp/lib/libavutil.so 0x41397cb0, skipping init
	06-23 20:40:20.416    2256-2256/com.example.testrtmp D/dalvikvm﹕ Trying to load lib /data/data/com.example.testrtmp/lib/libswresample.so 0x41397cb0
	06-23 20:40:20.436    2256-2256/com.example.testrtmp D/dalvikvm﹕ Added shared lib /data/data/com.example.testrtmp/lib/libswresample.so 0x41397cb0
	06-23 20:40:20.436    2256-2256/com.example.testrtmp D/dalvikvm﹕ No JNI_OnLoad found in /data/data/com.example.testrtmp/lib/libswresample.so 0x41397cb0, skipping init
	06-23 20:40:20.436    2256-2256/com.example.testrtmp D/dalvikvm﹕ Trying to load lib /data/data/com.example.testrtmp/lib/libavcodec.so 0x41397cb0
	06-23 20:40:20.506    2256-2256/com.example.testrtmp D/dalvikvm﹕ Added shared lib /data/data/com.example.testrtmp/lib/libavcodec.so 0x41397cb0
	06-23 20:40:20.506    2256-2256/com.example.testrtmp D/dalvikvm﹕ No JNI_OnLoad found in /data/data/com.example.testrtmp/lib/libavcodec.so 0x41397cb0, skipping init
	06-23 20:40:20.506    2256-2256/com.example.testrtmp D/dalvikvm﹕ Trying to load lib /data/data/com.example.testrtmp/lib/libavformat.so 0x41397cb0
	06-23 20:40:20.536    2256-2256/com.example.testrtmp D/dalvikvm﹕ Added shared lib /data/data/com.example.testrtmp/lib/libavformat.so 0x41397cb0
	06-23 20:40:20.536    2256-2256/com.example.testrtmp D/dalvikvm﹕ No JNI_OnLoad found in /data/data/com.example.testrtmp/lib/libavformat.so 0x41397cb0, skipping init
	06-23 20:40:20.536    2256-2256/com.example.testrtmp D/dalvikvm﹕ Trying to load lib /data/data/com.example.testrtmp/lib/libffmpeg_mediaplayer_jni.so 0x41397cb0
	06-23 20:40:20.666    2256-2256/com.example.testrtmp D/dalvikvm﹕ Added shared lib /data/data/com.example.testrtmp/lib/libffmpeg_mediaplayer_jni.so 0x41397cb0
	06-23 20:40:20.666    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer-JNI﹕ native_init
	06-23 20:40:20.876    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer-JNI﹕ native_setup
	06-23 20:40:20.876    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ constructor
	06-23 20:40:20.876    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ setListener
	06-23 20:40:21.287    2256-2256/com.example.testrtmp D/TextLayoutCache﹕ Using debug level: 0 - Debug Enabled: 0
	06-23 20:40:21.477    2256-2256/com.example.testrtmp D/libEGL﹕ loaded /system/lib/egl/libGLES_android.so
	06-23 20:40:21.577    2256-2256/com.example.testrtmp D/libEGL﹕ loaded /system/lib/egl/libEGL_mali.so
	06-23 20:40:21.617    2256-2256/com.example.testrtmp D/libEGL﹕ loaded /system/lib/egl/libGLESv1_CM_mali.so
	06-23 20:40:21.617    2256-2256/com.example.testrtmp D/libEGL﹕ loaded /system/lib/egl/libGLESv2_mali.so
	06-23 20:40:21.677    2256-2256/com.example.testrtmp D/OpenGLRenderer﹕ Enabling debug mode 0
	06-23 20:41:19.564    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ isPlaying: no active player
	06-23 20:41:19.564    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer-JNI﹕ isPlaying: 0
	06-23 20:41:19.574    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer-JNI﹕ setDataSource: path rtmp://192.168.1.10/myapp/aaa
	06-23 20:41:19.574    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ setDataSource(rtmp://192.168.1.10/myapp/aaa)
	06-23 20:41:19.584    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ prepareAsync
	06-23 20:41:19.584    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ MediaPlayer::setAudioStreamType
	06-23 20:41:19.614    2256-2595/com.example.testrtmp V/FFmpegMediaPlayer﹕ message received msg=100, ext1=1, ext2=0
	06-23 20:41:19.614    2256-2595/com.example.testrtmp E/FFmpegMediaPlayer﹕ error (1, 0)
	06-23 20:41:19.614    2256-2595/com.example.testrtmp V/FFmpegMediaPlayer﹕ callback application
	06-23 20:41:19.614    2256-2595/com.example.testrtmp V/FFmpegMediaPlayer-JNI﹕ notify: 100
	06-23 20:41:19.614    2256-2595/com.example.testrtmp V/FFmpegMediaPlayer﹕ back from callback
	06-23 20:41:19.614    2256-2256/com.example.testrtmp E/FFmpegMediaPlayer﹕ Error (1,0)
	06-23 20:41:19.624    2256-2256/com.example.testrtmp I/System.out﹕ Error 1 / Extra
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer-JNI﹕ release
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ setListener
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ disconnect
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ destructor
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ disconnect
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer-JNI﹕ native_setup
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ constructor
	06-23 20:41:19.624    2256-2256/com.example.testrtmp V/FFmpegMediaPlayer﹕ setListener

I'm using an Xperia Sola with Android 4.0.4.
I tried to build the library manually with ssl but then, when I run the app, it crashes at start up with the following log:

	06-23 21:21:28.144    4723-4723/com.example.testrtmp D/dalvikvm﹕ GC_FOR_ALLOC freed 64K, 9% free 9283K/10143K, paused 29ms
	06-23 21:21:28.154    4723-4723/com.example.testrtmp I/dalvikvm-heap﹕ Grow heap (frag case) to 10.697MB for 1639696-byte allocation
	06-23 21:21:28.194    4723-4732/com.example.testrtmp D/dalvikvm﹕ GC_FOR_ALLOC freed 3K, 8% free 10881K/11811K, paused 19ms
	06-23 21:21:28.354    4723-4723/com.example.testrtmp D/dalvikvm﹕ Trying to load lib /data/data/com.example.testrtmp/lib/libavutil.so 0x413a15b0
	06-23 21:21:28.374    4723-4723/com.example.testrtmp W/dalvikvm﹕ Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lwseemann/media/FFmpegMediaPlayer;
	06-23 21:21:28.374    4723-4723/com.example.testrtmp D/AndroidRuntime﹕ Shutting down VM
	06-23 21:21:28.374    4723-4723/com.example.testrtmp W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x40a9e210)
	06-23 21:21:28.414    4723-4723/com.example.testrtmp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
            at com.example.testrtmp.MainActivity.prepareFFMpeg(MainActivity.java:52)
            at com.example.testrtmp.MainActivity.onCreate(MainActivity.java:48)
            at android.app.Activity.performCreate(Activity.java:4465)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
            at android.app.ActivityThread.access$600(ActivityThread.java:127)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4448)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
            at dalvik.system.NativeStart.main(Native Method)
	Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1285]:  1428 cannot locate '__aeabi_ldiv0'...
            at java.lang.Runtime.loadLibrary(Runtime.java:370)
            at java.lang.System.loadLibrary(System.java:535)
            at wseemann.media.FFmpegMediaPlayer.<clinit>(FFmpegMediaPlayer.java:620)
            at com.example.testrtmp.MainActivity.prepareFFMpeg(MainActivity.java:52)
			at com.example.testrtmp.MainActivity.onCreate(MainActivity.java:48)
			at android.app.Activity.performCreate(Activity.java:4465)
			at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
			at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
			at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
			at android.app.ActivityThread.access$600(ActivityThread.java:127)
			at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
			at android.os.Handler.dispatchMessage(Handler.java:99)
			at android.os.Looper.loop(Looper.java:137)
			at android.app.ActivityThread.main(ActivityThread.java:4448)
			at java.lang.reflect.Method.invokeNative(Native Method)
			at java.lang.reflect.Method.invoke(Method.java:511)
			at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:823)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:590)
			at dalvik.system.NativeStart.main(Native Method)

Please, is there anything else that I can do to solve this for my phone?

**Comment by reyalpsirc** [comment]
Nevermind, I just forgot to add the permissions to the manifest...

    <uses-permission android:name="android.permission.BROADCAST_STICKY" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

**Comment by rayrachet** [comment]
Code.?

**Comment by reyalpsirc** [comment]
I made a wrapper class for it and so, here's the code:

    public class RTMPReader {

        FFmpegMediaPlayer player;
        boolean playing=false;

        public interface IStart{
            public void OnStart();
        }

        public interface IStop{
            public void OnStop();
        }

        private IStart startCallback;
        private IStop stopCallback;

        public void setStartCallback(IStart startCallback){
            this.startCallback=startCallback;
        }

        public void setStopCallback(IStop stopCallback){
            this.stopCallback=stopCallback;
        }

        public void start(String rtmpLink){
            try {
                playing=true;
                player = new FFmpegMediaPlayer();
                player.reset();
                player.setOnPreparedListener(null);
                player.setDataSource(rtmpLink);
                player.setOnPreparedListener(new FFmpegMediaPlayer.OnPreparedListener() {

                    @Override
                    public void onPrepared(FFmpegMediaPlayer mp) {
                        player.start();
                    }
                });
                player.setOnErrorListener(new FFmpegMediaPlayer.OnErrorListener() {

                    @Override
                    public boolean onError(FFmpegMediaPlayer mp, int what, int extra) {
                        player.release();
                        player=null;
                        stop();
                        return false;
                    }
                });
                player.prepareAsync();
                if (startCallback!=null)
                    startCallback.OnStart();
            } catch (IllegalArgumentException e) {
                player=null;
                stop();
                e.printStackTrace();
            } catch (SecurityException e) {
                player=null;
                stop();
                e.printStackTrace();
            } catch (IllegalStateException e) {
                player=null;
                stop();
                e.printStackTrace();
            } catch (IOException e) {
                player=null;
                stop();
                e.printStackTrace();
            }
        }

        public void stop(){
            playing=false;
            if (player!=null){
                player.stop();
            }
            if (stopCallback!=null)
                stopCallback.OnStop();
        }

        public boolean isPlaying(){
            return playing;
        }
    }

**Comment by SohailZahidGit** [comment]
Unable to play video file form local storage did you people find any solution.
