### ISSUE TITLE
OpenSSL

### ISSUE THREAD

**Issue by Platane** [wseemann/FFmpegMediaPlayer#57]
Hello,

I use FFmpegMediaPlayer to stream over https connection.

The Google play team sent me a mail saying that my OpenSSL version is obsolete. Actually app that does not have a recent OpenSSL lib will not be able to be updated soon.

I tried to build FFmpegMediaPlayer replacing openssl-android.tar.gz with an updated version that I found in your repositories list ( https://github.com/wseemann/openssl-android). but the build failed

```
     [exec] make: *** No rule to make target `jni/openssl-android/crypto/aes/asm/aes-armv4.S', needed by `jni/openssl-android/obj/local/armeabi/objs/crypto/aes/asm/aes-armv4.o'.  Stop.

BUILD FAILED
/FFmpegMediaPlayer/fmp-library/custom_rules.xml:46: exec returned: 2
```

I am not sure that I have the knowledges to fix this, but I will try and keep you updated.
If you have any clues to do so ...

thanks

**Comment by songhaonangit** [comment]
I meet the same bug ，and I found in your repositories list ( https://github.com/wseemann/openssl-android). but the build failed.

**Comment by songhaonangit** [comment]
@wseemann how to fix it ?
