### ISSUE TITLE
fatal signal 11 Error

### ISSUE THREAD

**Issue by sharath2mobile** [wseemann/FFmpegMediaPlayer#60]
Dear wseemann,

Thanks for the android FFmpegMediaPlayer -library that help me to play audio steams like MP3 and AAC.

I found the issue " fatal signal 11 (sigsegv) FFmpegMediaPlayer " when click on media player next button.when single streaming is playing it is working fine and buffering also displaying on the console.The Issue is found when clicking on the media player next button.

I am using the latest provided pre-complied ".so" files as described in the "README.md".

can you please look at the Issue.

Thanks,
sharath.

**Comment by pfaffenrodt** [comment]
It is related with #29

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
