### ISSUE TITLE
MalformedURLException: Unknown protocol: rtmp

### ISSUE THREAD

**Issue by dairdr** [wseemann/FFmpegMediaPlayer#63]
I send a String URL like rtmp://173.199.148.4:1935/live/radiomonteria to setDataSource method, but console shows: W/System.err﹕ java.net.MalformedURLException: Unknown protocol: rtmp

Supported protocols:

file, http, https, mms, mmsh and rtmp

Thanks

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
