### ISSUE TITLE
getAudioSessionId return 0

### ISSUE THREAD

**Issue by hnvn** [wseemann/FFmpegMediaPlayer#66]
I'm trying to use Visualizer with FFmpegMediaPlayer, but I've a problem: FFmpegMediaPlayer.getAudioSessionId return 0, so that I can't create Visualizer. Anyone help me?

**Comment by wnpllrzodiac** [comment]
0 means mixer?
I think ONLY system player has meaningful session id?

**Comment by wseemann** [comment]
The library now uses OpenSL ES for audio playback. This API doesn't provide a way to obtain a non-zero session id. Hence, the library always returns 0.
