### ISSUE TITLE
prebuilt so library can not be found ?? 404

### ISSUE THREAD

**Issue by simplePig** [wseemann/FFmpegMediaPlayer#68]
at "https://github.com/wseemann/FFmpegMediaPlayer/blob/master/fmp-library/prebuilt-libs.tar.gz." 
is 404 page , can you update it? fix it issue...

**Comment by zarej** [comment]
Try this:
https://github.com/wseemann/FFmpegMediaPlayer/blob/master/gradle/fmp-library/prebuilt-libs.tar.gz

Note there is added /gradle folder in path

**Comment by wseemann** [comment]
See the release page: https://github.com/wseemann/FFmpegMediaPlayer/releases/
