### ISSUE TITLE
Getting crash randomly while playing audio streams

### ISSUE THREAD

**Issue by atul14** [wseemann/FFmpegMediaPlayer#69]
Getting crash randomly while attempting to play audio streams. Following is the crash trace 

11-04 12:57:43.511 28898-7896/com.demo W/FFmpegMediaPlayer-JNI: An exception occurred while notifying an event.
11-04 12:57:43.511 28898-7896/com.demo A/libc: Fatal signal 11 (SIGSEGV) at 0x00000cb5 (code=1), thread 7896 (m.demo)
11-04 12:57:43.531 28898-28898/com.demo D/dalvikvm: GC_FOR_ALLOC freed 68K, 23% free 12730K/16408K, paused 17ms, total 17ms
11-04 12:57:43.561 1182-1182/? I/Keyboard.Facilitator: onFinishInput()
11-04 12:57:43.661 221-221/? I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-04 12:57:43.671 221-221/? I/DEBUG: Build fingerprint: 'Lenovo/Kraft-A6000/Kraft-A6000:4.4.4/KTU84P/Kraft-A6000_S040_150805:user/release-keys'
11-04 12:57:43.681 221-221/? I/DEBUG: Revision: '0'
11-04 12:57:43.691 221-221/? I/DEBUG: pid: 28898, tid: 7896,  >>> com.demo <<<
11-04 12:57:43.701 221-221/? I/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000cb5
11-04 12:57:43.721 226-600/? I/EffectDs: Effect_process(b81f2db0) called on session 0 (logs suppressed for next second) (inBuffer==outBuffer)?TRUE! outputConfig.accessMode=WRITE
11-04 12:57:44.091 221-221/? I/DEBUG:     r0 7f9292b8  r1 80d78c60  r2 00000000  r3 00000c89
11-04 12:57:44.091 221-221/? I/DEBUG:     r4 7f9292b8  r5 80d78c60  r6 7f9292b8  r7 00000000
11-04 12:57:44.091 221-221/? I/DEBUG:     r8 782087f9  r9 809701ec  sl 7f929788  fp 00023bde
11-04 12:57:44.091 221-221/? I/DEBUG:     ip 80977d18  sp 80d78b38  lr 809441a8  pc 809441b4  cpsr 680f0010
11-04 12:57:44.091 221-221/? I/DEBUG:     d0  657665206e612067  d1  6572727563636f20
11-04 12:57:44.091 221-221/? I/DEBUG:     d2  20656c6968772064  d3  6e69796669746f6e
11-04 12:57:44.091 221-221/? I/DEBUG:     d4  2e0f2b7a2dc42b3e  d5  2e582bc92e3f2ba5
11-04 12:57:44.091 221-221/? I/DEBUG:     d6  2e742c1d2e652bee  d7  2e7b2c632e832c4e
11-04 12:57:44.091 221-221/? I/DEBUG:     d8  0000000000000001  d9  4434000042980000
11-04 12:57:44.091 221-221/? I/DEBUG:     d10 4076800044548000  d11 0000000000000000
11-04 12:57:44.091 221-221/? I/DEBUG:     d12 0000000000000000  d13 0000000000000000
11-04 12:57:44.091 221-221/? I/DEBUG:     d14 0000000000000000  d15 0000000000000000
11-04 12:57:44.091 221-221/? I/DEBUG:     d16 0000000000000000  d17 0000000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     d18 412e848000000000  d19 8000000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     d20 8000000000000000  d21 3ff0000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     d22 8000000000000000  d23 0000000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     d24 0000000000000000  d25 0000000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     d26 0000000000000000  d27 0000000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     d28 0000000000000000  d29 0000000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     d30 0000000000000000  d31 4000000000000000
11-04 12:57:44.101 221-221/? I/DEBUG:     scr 68000013
11-04 12:57:44.101 221-221/? I/DEBUG:     #00  pc 0008c1b4  /data/app-lib/com.demo-1/libavformat.so
11-04 12:57:44.101 221-221/? I/DEBUG:     #01  pc 0008c1a4  /data/app-lib/com.demo-1/libavformat.so
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78af8  80d78c14  [stack:7896]
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78afc  4156bdf0  /system/lib/libdvm.so (dvmMterpStd(Thread*)+80)
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b00  41be5c08  /dev/ashmem/dalvik-heap (deleted)
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b04  7aeda758  
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b08  00000000  
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b0c  6ee93e42  /system/framework/framework.odex
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b10  763aefb0  
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b14  fffffe4c  
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b18  4156bda0  /system/lib/libdvm.so (dvmMterpStd(Thread*))
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b1c  41569488  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+188)
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b20  4156bda0  /system/lib/libdvm.so (dvmMterpStd(Thread*))
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b24  00000000  
11-04 12:57:44.101 221-221/? I/DEBUG:          80d78b28  80d78c40  [stack:7896]
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b2c  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b30  763aefb0  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b34  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     #00  80d78b38  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          ........  ........
11-04 12:57:44.111 221-221/? I/DEBUG:     #01  80d78b38  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b3c  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b40  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b44  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b48  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b4c  80967e7e  /data/app-lib/com.demo-1/libavformat.so
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b50  d2a7f45f  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b54  3e730593  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b58  42980000  /dev/ashmem/dalvik-heap (deleted)
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b5c  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b60  7f9292b8  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b64  7f9292b8  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b68  80d78d48  [stack:7896]
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b6c  782087f9  /data/app-lib/com.demo-1/libffmpeg_mediaplayer_jni.so (player_decode)
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b70  80c7b000  
11-04 12:57:44.111 221-221/? I/DEBUG:          80d78b74  00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f929298 00000000 00000000 00000088 0000001a  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f9292a8 6d577120 00000014 00000000 00000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f9292b8 00000001 00000c89 7f9292b8 7f9292b8  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f9292c8 00000000 00000000 400f22dc 00000007  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f9292d8 00000000 f9000000 f9000000 f9000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f9292e8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f9292f8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f929308 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f929318 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.111 221-221/? I/DEBUG:     7f929328 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929338 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929348 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929358 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929368 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929378 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929388 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78c40 80d78d48 41577deb 415e1441 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78c50 7aeda758 00000000 415f78f4 00008000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78c60 00000000 415883c5 00000000 80000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78c70 00000000 80000000 00000000 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78c80 00000000 00000000 00000000 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78c90 00000000 00000000 00001200 400b1d55  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78ca0 ffffffff ffffffff 00000000 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78cb0 00000003 7f9292c0 7f9292b8 00000001  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78cc0 80d78d48 782087f9 80c7b000 7f9292dc  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78cd0 400f02ec 80946b68 00000000 7f3766e0  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78ce0 782087f9 400b543f 400ee000 80d78d14  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78cf0 400ee000 80d78d70 00000000 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78d00 dfb9b0bb 7f9292c0 7820cfaa 00000001  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78d10 dfb9b0bb 782087f9 80c7b000 7f9292dc  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78d20 400f02ec 782088f7 00000000 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     80d78d30 00000000 00000000 00000000 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929298 00000000 00000000 00000088 0000001a  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f9292a8 6d577120 00000014 00000000 00000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f9292b8 00000001 00000c89 7f9292b8 7f9292b8  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f9292c8 00000000 00000000 400f22dc 00000007  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f9292d8 00000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f9292e8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f9292f8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929308 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929318 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.121 221-221/? I/DEBUG:     7f929328 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929338 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929348 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929358 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929368 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929378 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929388 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78c40 80d78d48 41577deb 415e1441 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78c50 7aeda758 00000000 415f78f4 00008000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78c60 00000000 415883c5 00000000 80000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78c70 00000000 80000000 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78c80 00000000 00000000 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78c90 00000000 00000000 00001200 400b1d55  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78ca0 ffffffff ffffffff 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78cb0 00000003 7f9292c0 7f9292b8 00000001  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78cc0 80d78d48 782087f9 80c7b000 7f9292dc  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78cd0 400f02ec 80946b68 00000000 7f3766e0  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78ce0 782087f9 400b543f 400ee000 80d78d14  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78cf0 400ee000 80d78d70 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78d00 dfb9b0bb 7f9292c0 7820cfaa 00000001  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78d10 dfb9b0bb 782087f9 80c7b000 7f9292dc  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78d20 400f02ec 782088f7 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78d30 00000000 00000000 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929298 00000000 00000000 00000088 0000001a  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9292a8 6d577120 00000014 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9292b8 00000001 00000c89 7f9292b8 7f9292b8  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9292c8 00000000 00000000 400f22dc 00000007  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9292d8 00000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9292e8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9292f8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929308 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929318 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929328 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929338 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929348 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929358 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929368 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929378 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929388 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     782087d8 0000483f 0000493d 000047f1 00004912  
11-04 12:57:44.131 221-221/? I/DEBUG:     782087e8 000047a9 000048f2 000067d8 000048e8  
11-04 12:57:44.131 221-221/? I/DEBUG:     782087f8 43f0e92d 4d54b09d 447d4604 2b006a23  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208808 809cf040 6aa26a63 d0084293 682062a3  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208818 f7fdb11b 64a0eaee f7fde001 6ae3eaf0  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208828 d0572b00 0110e9d4 890ee9d4 f1712801  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208838 db0a0300 464f4646 1a362202 0701eb67  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208848 18b62300 0703eb47 ea50e014 d00e0301  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208858 0000ebb8 0101eb69 0201f06f f04f1880  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208868 f04f33ff eb414700 26000103 2600e006  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208878 4700f04f 30fff04f 4100f06f 46326b23  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208888 0102e9cd 31fff04f 93046820 e9cd463b  
11-04 12:57:44.131 221-221/? I/DEBUG:     78208898 f7fd8900 2800eaba 482cda09 68224629  
11-04 12:57:44.131 221-221/? I/DEBUG:     782088a8 68004478 322030a8 eab4f7fd 6863e010  
11-04 12:57:44.131 221-221/? I/DEBUG:     782088b8 db032b00 689868e3 eab2f7fd 23012200  
11-04 12:57:44.131 221-221/? I/DEBUG:     782088c8 6c58f8d4 93002104 f8d44613 47b00c64  
11-04 12:57:44.131 221-221/? I/DEBUG:     809701cc 0001100d 00000001 00015001 00000002  
11-04 12:57:44.131 221-221/? I/DEBUG:     809701dc 00010000 00000003 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     809701ec 00000018 0000001e 0000003c 0000000c  
11-04 12:57:44.131 221-221/? I/DEBUG:     809701fc 0000000f 00000030 00000001 000f4240  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097020c 675f6666 735f6e65 63726165 31300068  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097021c 35343332 39383736 64636261 31306665  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097022c 35343332 39383736 44434241 00004645  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097023c 7a670100 d4b62910 19332220 212363c6  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097024c ce981101 21181933 65463a03 ad24656a  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097025c 143212e9 ad34261a 238241a4 1a2b5001  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097026c 30486924 12112e40 048cc608 344c2841  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097027c 13011ef0 603ce0f2 00282020 08000300  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097028c 01030000 00000094 ce680100 00d04833  
11-04 12:57:44.131 221-221/? I/DEBUG:     8097029c 67010000 a628106e 333220d4 8818710c  
11-04 12:57:44.131 221-221/? I/DEBUG:     809702ac 19191062 448c3886 56022130 87616e4e  
11-04 12:57:44.131 221-221/? I/DEBUG:     809702bc 984d733e 9c06030c c0e6730b 0d6318b5  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929768 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929778 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929788 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929798 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9297a8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9297b8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9297c8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9297d8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9297e8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f9297f8 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929808 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929818 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929828 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929838 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929848 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     7f929858 f9000000 f9000000 f9000000 f9000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023bbc ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023bcc ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023bdc ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023bec ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023bfc ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c0c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c1c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c2c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c3c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c4c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c5c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c6c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c7c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c8c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023c9c ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     00023cac ffffffff ffffffff ffffffff ffffffff  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977cf8 777cff00 777cae3c 777c1fe4 777cb68c  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d08 777d057c 77afcd44 779c92a8 777d4704  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d18 7798f1f0 779c92cc 777cb88c 777c1ce4  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d28 400cf501 400a0d25 400c4ca0 400c4594  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d38 400b8631 777c7054 400c4da0 400a0e1d  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d48 400c44a0 779e3570 779e3444 777c21bc  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d58 400de5fb 7798fef8 77b13f6c 777caad8  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d68 777caeb4 777cb904 777c4c58 777c2304  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d78 400cfe71 777c06ec 777cdbb4 400cfa81  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d88 402654e0 777c1d34 777c1da0 400cf659  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977d98 777c1f28 402634fc 402691ac 400a0c91  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977da8 777c1edc 777c20f4 777c4cb4 40263788  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977db8 777cb498 777c2528 777c1e90 777d1540  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977dc8 777cb450 777cb458 777cb53c 77b52458  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977dd8 402690e8 777c8e30 400c4cc0 777d0d0c  
11-04 12:57:44.131 221-221/? I/DEBUG:     80977de8 77b571d0 77ad0db4 777cb6b8 77b524a8  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78b18 4156bda0 41569488 4156bda0 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78b28 80d78c40 00000000 763aefb0 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78b38 00000000 00000000 00000000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78b48 00000000 80967e7e d2a7f45f 3e730593  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78b58 42980000 00000000 7f9292b8 7f9292b8  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78b68 80d78d48 782087f9 80c7b000 00000000  
11-04 12:57:44.131 221-221/? I/DEBUG:     80d78b78 80967ff2 809466fc 00000000 00000000  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78b88 00000000 00000000 400f2394 00000000  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78b98 000217c1 80968073 00000000 80d78c14  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78ba8 00000000 4159e5c3 00000000 00000000  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78bb8 00000000 00000000 802cd798 41538f10  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78bc8 7f928700 00000000 41604528 7f928708  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78bd8 7aeda750 00000000 41604528 7aeda758  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78be8 00000000 400b543f 400ee000 7aeda758  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78bf8 7aeda758 00000000 41604528 400b1d55  
11-04 12:57:44.141 221-221/? I/DEBUG:     80d78c08 00000000 415928f9 41c120c8 6d8dc2a0  
11-04 12:57:44.141 1056-1056/? D/wpa_supplicant: RX ctrl_iface - hexdump(len=11): 53 49 47 4e 41 4c 5f 50 4f 4c 4c
11-04 12:57:44.141 1056-1056/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
11-04 12:57:44.141 221-221/? I/DEBUG:     80944194 e3a03000 e1a00005 e5853018 e585301c  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441a4 ebfdfc1e e5943004 e1a00004 e1a01005  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441b4 e593302c e12fff33 e2508000 aa000026  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441c4 e378000b 13570000 13a07000 03a07001  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441d4 1a00001d ea00006e e594301c e7936107  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441e4 e59630e4 e3530000 0a000006 e59631b8  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441f4 e3530000 da000003 e1a00004 e1a01006  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944204 e3a02000 ebfffe1a e59631b8 e3530000  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944214 da00000c e59f3190 e3a00000 e59f218c  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944224 e1a01000 e08f3003 e58d3000 e30032ad  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944234 e58d3004 e59f3178 e08f2002 e08f3003  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944244 ebfdfb27 ebfdfb38 e2877001 e5943018  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944254 e1570003 3affffdf eaffffab e594343c  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944264 e3130c01 0a00000a e5952024 e3120002  
11-04 12:57:44.141 1056-1056/? D/wpa_supplicant: nl80211: survey data missing!
11-04 12:57:44.141 221-221/? I/DEBUG:     80944274 0a000007 e1a00004 e3a01018 e59d2014  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944284 e5953020 ebfdfb16 e1a00005 ebfdfb0b  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944188 ebfdfb53 e3a00000 ea000081 e3a03000  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944198 e1a00005 e5853018 e585301c ebfdfc1e  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441a8 e5943004 e1a00004 e1a01005 e593302c  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441b8 e12fff33 e2508000 aa000026 e378000b  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441c8 13570000 13a07000 03a07001 1a00001d  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441d8 ea00006e e594301c e7936107 e59630e4  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441e8 e3530000 0a000006 e59631b8 e3530000  
11-04 12:57:44.141 221-221/? I/DEBUG:     809441f8 da000003 e1a00004 e1a01006 e3a02000  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944208 ebfffe1a e59631b8 e3530000 da00000c  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944218 e59f3190 e3a00000 e59f218c e1a01000  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944228 e08f3003 e58d3000 e30032ad e58d3004  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944238 e59f3178 e08f2002 e08f3003 ebfdfb27  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944248 ebfdfb38 e2877001 e5943018 e1570003  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944258 3affffdf eaffffab e594343c e3130c01  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944268 0a00000a e5952024 e3120002 0a000007  
11-04 12:57:44.141 221-221/? I/DEBUG:     80944278 e1a00004 e3a01018 e59d2014 e5953020

**Comment by pfaffenrodt** [comment]
NDK Stack would be more useful.
https://developer.android.com/ndk/guides/ndk-stack.html
```
adb logcat | $NDK/ndk-stack -sym $PROJECT_PATH/obj/local/armeabi
```
This Bug maybe related with #29

**Comment by atul14** [comment]
Hi Thanks for revert.

Yes, exactly the bug is linked to #29 

The solution mentioned in that works?

**Comment by pfaffenrodt** [comment]
yes
