### ISSUE TITLE
FFMpeg with Android phonegap

### ISSUE THREAD

**Issue by varsha123** [wseemann/FFmpegMediaPlayer#7]
Hi

As android native media player taking time to play cloudfront mp3 stream url's...
I have integrated FFmpeg libarary in android phone gap plugin to play .mp3 files from amazon cloud-front.
We have list of songs and onclick of each track we are playing that track song mp3 file..
I am able to play first 2 songs successfully but while playing song we are getting below error:
13:08:20.990: A/libc(12950): Fatal signal 11 (SIGSEGV) at 0x00000018 (code=1), thread 13352 (WebViewCoreThre)..
on android version 4.2.1 model number Spcice Mi-525.

Kindly provide solution to resolve this issue..

Thanks
Varsha

**Comment by ashokkumar88** [comment]
Hi Varshan,

Can u pls share the ffmpeg phonegap plugin? I need it for my project. Pls help

**Comment by wseemann** [comment]
Phonegap is not supported.
