### ISSUE TITLE
build-ffmpeg.sh bad variable name

### ISSUE THREAD

**Issue by osugo** [wseemann/FFmpegMediaPlayer#71]
I have added the  library to my project successfully but after replacing the Android media player with the FFmpegMediaPlayer and trying to build and run the project, i get the following error:

:library:buildFFmpeg
/home/kombo/Radio Africa/Music Player/library/src/main/scripts/build-ffmpeg.sh: 4: export: Africa/Music: bad variable name

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:buildFFmpeg'.
> Process 'command '/home/kombo/Radio Africa/Music Player/library/src/main/scripts/build-ffmpeg.sh'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 34.148 secs

How can i solve tackle this since removing the build-ffmpeg.sh file doesn't look like an option.

**Comment by pfaffenrodt** [comment]
I would not recommend to add this project as module. Use the prebuilds or build it in a separat project.

**Comment by thaKombo** [comment]
I managed to get the project to compile and run using the aar file you provided above, thanks, but now i have a new problem, every time i try to play any audio file, i get this response:

1-06 14:28:26.490 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer-JNI: native_setup
11-06 14:28:26.490 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: constructor
11-06 14:28:26.490 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: setListener
11-06 14:28:26.490 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer-JNI: setAudioStreamType: 3
11-06 14:28:26.490 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: MediaPlayer::setAudioStreamType
11-06 14:28:26.490 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer-JNI: setDataSource: path mmsh:/stream.kbc.co.ke:8083
11-06 14:28:26.490 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: setDataSource(mmsh:/stream.kbc.co.ke:8083)
11-06 14:28:26.490 21385-21385/com.radioafrica.music E/Stream: mms://stream.kbc.co.ke:8083
11-06 14:28:26.490 21385-21385/com.radioafrica.music E/AudioManager: Player entry present, no need to add
11-06 14:28:26.494 21385-21385/com.radioafrica.music V/AudioManager: updating focussed RCC change to RCD: CallingPackageName:com.radioafrica.music
11-06 14:28:26.516 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: prepareAsync
11-06 14:28:26.516 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: MediaPlayer::setAudioStreamType
11-06 14:28:43.535 21385-25001/com.radioafrica.music V/FFmpegMediaPlayer: message received msg=100, ext1=1, ext2=0
11-06 14:28:43.535 21385-25001/com.radioafrica.music E/FFmpegMediaPlayer: error (1, 0)
11-06 14:28:43.535 21385-25001/com.radioafrica.music V/FFmpegMediaPlayer: callback application
11-06 14:28:43.535 21385-25001/com.radioafrica.music V/FFmpegMediaPlayer-JNI: notify: 100
11-06 14:28:43.537 21385-21385/com.radioafrica.music E/FFmpegMediaPlayer: Error (1,0)
11-06 14:28:43.537 21385-25001/com.radioafrica.music V/FFmpegMediaPlayer: back from callback
11-06 14:28:43.581 21385-21385/com.radioafrica.music E/Music: Error: what=1, extra=0
11-06 14:28:43.584 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer-JNI: reset
11-06 14:28:43.584 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: reset
11-06 14:28:43.584 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer-JNI: release
11-06 14:28:43.584 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: setListener
11-06 14:28:43.584 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: disconnect
11-06 14:28:43.584 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: destructor
11-06 14:28:43.584 21385-21385/com.radioafrica.music V/FFmpegMediaPlayer: disconnect
