### ISSUE TITLE
RTMP streaming. Cannot pass get parameters

### ISSUE THREAD

**Issue by IlyaMyasoedov** [wseemann/FFmpegMediaPlayer#74]
Good day !!! I develop the app that uses RTMP protocol for streaming mp3 files. I need to pass get parameters through the request "rtmp://178.132.203.158:1935/music/_definst_/mp3:a33/yb5/gsa/a33yb5gsa370.mp3?wowzartmpstart=1792&wowzartmpduration=20000" but these parameters are not received by the server when i use FFMediaPlayer class.

**Comment by wnpllrzodiac** [comment]
ffmpeg build-in librtmp?

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
