### ISSUE TITLE
Cannot stream mms on lollipop

### ISSUE THREAD

**Issue by branemk** [wseemann/FFmpegMediaPlayer#76]
I am using this library for streaming radio . Recently one of the stations changed their stream to mms and everything works ok on kitkat and below , but on lollipop an up I am getting error (1, 0) . 

Also I am getting Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 12834 (Thread-257) is try to put mmsh stream . 

And can you tell me are you planing to update this lib ?

**Comment by wseemann** [comment]
This should be fixed in version [1.0.1](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.1).
