### ISSUE TITLE
Cannot install lib

### ISSUE THREAD

**Issue by fxhereng** [wseemann/FFmpegMediaPlayer#78]
I followed the steps of installation, extract prebuilt modules in libs, but I can't import it on my project. The class "FFmpegMediaPlayer" isn't available.

Could you please explain the install process?

Thanks!

**Comment by osugo** [comment]
Download the aar file from here [FMP aar file](https://github.com/wseemann/FFmpegMediaPlayer/tree/master/gradle/fmp-library/library/build/outputs/aar) and add it to  your project as a dependency

**Comment by fxhereng** [comment]
Thanks for your answer!

Unfortunately I didn't get it work yet...

I put the file it in my libs folder, then in my project gradle:
```
compile 'wseemann.media.ffmpegmediaplayer:1.0.0@aar'
```

or 
```
compile 'wseemann.media.ffmpegmediaplayer:all-fmp@aar'
```

and in my global gradle:
```
buildscript {
    repositories {
        jcenter()
        flatDir {
            dirs 'libs'
        }
    }
....
}
```

Doesn't work,

Thanks for helping!

**Comment by fxhereng** [comment]
EDIT: I finally got it worked thanks to this answer:

http://stackoverflow.com/a/30713617/4942969

**Comment by fxhereng** [comment]
It's still not compiling because I have FFmpegMediaPlayer and FFmpegMetadataRetriever working on the same project, this is my issue:

```
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.transform.api.TransformException: java.util.zip.ZipException: duplicate entry: wseemann/media/Metadata.class
```

I had a Dex error as well, I solved it putting:
```
    defaultConfig {
        .....
        multiDexEnabled true
        .....
 }
```

My build.gradle:
```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.******.********"
        multiDexEnabled true
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 7
        versionName "1.3.2"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile('com.github.afollestad.material-dialogs:core:0.8.5.4@aar') {
        //Material dialogs for android 4.xx
        transitive = true
    }
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.koushikdutta.ion:ion:2.1.7'
    compile 'com.github.wseemann:FFmpegMediaMetadataRetriever:1.0.4'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.google.android.gms:play-services-analytics:8.1.0'
    compile project(':FFmpegMediaPlayer')
}

```

**Comment by satyamub** [comment]
@fxhereng hi I am having issue importing this war file can you show me how did you write the compile statement to import this.

**Comment by fxhereng** [comment]
@satyamub You need to import a new project from aar file, then in your build.gradle:
```
compile project(':FFmpegMediaPlayer')
```

"FFmpegMediaPlayer" is the name of the imported project. 

My problem was that I have as well the FFmpegMediaRetriever which is other library, it seems to have conflicts between them, but apparently it has been solved recently: 

see https://github.com/wseemann/FFmpegMediaMetadataRetriever/issues/74#event-604539606 if you want to use both libraries.

**Comment by satyamub** [comment]
how do i import new project from afar file.. can you please give me steps..

Apparently now, I am including that fmp-all.aar file in libs and then in my grade I write this below code

 compile(name:'all-fmp', ext:'aar')

below that 

repositories{
    flatDir{
        dirs 'libs'
    }

}

Then i am importing the sample to check however when I include that .aidl file in "aidl folder" in my project, it complains...

**Comment by fxhereng** [comment]
I did like this: File -> New Module -> Import JAR or AAR Package

I followed this answer: http://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst/30713617#30713617

I think you doesn't need the flatDir statement with this solution.

Hope it helps!

**Comment by satyamub** [comment]
I tried that too from that same link.. when i include the all-fmp.aar through jar/aar module,,, it creates folder named after that same air file...then 

compile project(':FFmpegMediaPlayer')
it shows error. please rectify.

**Comment by fxhereng** [comment]
Can you copy error and your build.gradle please?

Do you have in your settings.gradle something like:
```
include ':app', ':FFmpegMediaPlayer'
```

?

**Comment by satyamub** [comment]
now errors have gone however when i am trying to play a video stream...it only plays audio???????

**Comment by tspvivek** [comment]
@satyamub  @fxhereng  Please give us the step by step procedure to use pre-built library. I tried for 2 days but each time i get different errors.

**Comment by satyamub** [comment]
what all steps have you followed so far?

**Comment by fxhereng** [comment]
1/ Download the aar file from [here](https://github.com/wseemann/FFmpegMediaPlayer/tree/master/gradle/fmp-library/library/build/outputs/aar) FMP aar file and add it to your project as a dependency

2/ File -> New Module -> Import JAR or AAR Package

3/ Add in your gradle: 
```
compile project(':FFmpegMediaPlayer')
```

4/ Run and tell us if it's working for you

**Comment by satyamub** [comment]
@tspvivek are you want to play video/audio in your application? if you want to play video...dont waste your time in this lib!!

**Comment by tspvivek** [comment]
@fxhereng  Thanks, this AAR file solved the issue. its working great.

**Comment by tspvivek** [comment]
@satyamub I want only audio support alone.

**Comment by fxhereng** [comment]
:+1:
