### ISSUE TITLE
How to get it working on android studio?

### ISSUE THREAD

**Issue by xMonty** [wseemann/FFmpegMediaPlayer#81]
I cant the thing to compile on android studio even after copying the libs there is just one error after another, does this lib support android studio?

**Comment by wseemann** [comment]
The "thing" you are referring to is software that took me quite some time to design and code. I offer prebuilt AAR's and gradle options to facilitate use in your project.

**Comment by xMonty** [comment]
I apologise i meant no disrespect i was just frustrated and my comment might have come across as being disrespectful, i appreciate you hard work and you sharing it with the world.
Can you point me to the AAR's and gradle options i cant seem to find them on the project page or github readme

**Comment by wseemann** [comment]
No problem, I appreciate you apologizing. The prebuilt AAR's are located [here](https://github.com/wseemann/FFmpegMediaPlayer/raw/master/gradle/fmp-library/prebuilt-libs.tar.gz). The first release of the library rewrite (in progress) AAR's can be found on the [releases](https://github.com/wseemann/FFmpegMediaPlayer/releases) page. Let me know if you have any questions.
