### ISSUE TITLE
Library not support https links

### ISSUE THREAD

**Issue by Amanysaid** [wseemann/FFmpegMediaPlayer#86]
Hi @wseemann, sorry to bother you .
Library description :
Supported protocols:
file, http, https, mms, mmsh and rtmp

 but new release of library not play https links and sound not pure

the old library work fine with voice but not support https link
What do you think about this?

**Comment by RayBa82** [comment]
https support would be really great.
Im not able to compile it with https support and I even need to play videos from servers with self signed certifiates.

An example https url is here https://wiki.yoctoproject.org/wiki/images/a/a6/Big-buck-bunny_trailer.webm

**Comment by wseemann** [comment]
These are available in the latest release, version 1.0.3.

**Comment by RayBa82** [comment]
https is still not working....
