### ISSUE TITLE
The create or preparing stage keeps on loading and file never loads, could not play audio file

### ISSUE THREAD

**Issue by GuneetSinghHoney** [wseemann/FFmpegMediaPlayer#87]
1) Library is included i can find and create object of this class successfully 
2) when i use  obj.**create**(getApplicationContext(),R.raw.song);
         or obj.**setDataSource**(some _file_ or even i have used _file descriptor_) and call **prepare()**;

3) It takes forever to load - therefore I can never call **start()** method 

- please tell solution

**Note:** I have even tried to run It on other Thread but that also failed
         and I have given Internet and storage permissions

**Comment by wseemann** [comment]
Can you post the output from logcat? Also, what device and version are you testing on?

**Comment by GuneetSinghHoney** [comment]
My _android studio_ is 1.5.1 

SDK : minSdkVersion 19
          targetSdkVersion 23

**testing device**: 1)samsung note 3 neo 
		2) android version 4.4.2 (kitkat)

**logicat** 
[logcat.txt](https://github.com/wseemann/FFmpegMediaPlayer/files/275327/logcat.txt)

and my **Mainactivity**
[program.txt](https://github.com/wseemann/FFmpegMediaPlayer/files/275329/program.txt)


dependency in applications build.gradle
 compile(name:'armv7-fmp', ext:'aar')
where file(armsv7-fmp.aar) is in libs folder

**Comment by wseemann** [comment]
Can you send me you code and/or the file you are trying to play. I've 
tried for several hours to reproduce this issue using the emulator and I 
don't see any issues.

**Comment by GuneetSinghHoney** [comment]
Hello Sir, Player is working now. But the only problem left is it takes  much time to perpare Player.  I am sending files. Please help me.
I used your files as it it, with no change. FFMPegMediaPlayer, Metadata, TimedText. It takes 7 to 10 seconds. please help me to reduce this buffer time. I have used following streaming link.

http://173.192.105.231:8459/Live

**Comment by wseemann** [comment]
To reduce the buffer size change the value of `MAX_AUDIOQ_SIZE` in [ffmpeg_mediaplayer.h](https://github.com/wseemann/FFmpegMediaPlayer/blob/master/gradle/fmp-library/library/src/main/jni/player/ffmpeg_mediaplayer.h).
