### ISSUE TITLE
Audio with noise

### ISSUE THREAD

**Issue by w7virtual** [wseemann/FFmpegMediaPlayer#90]
When streaming audio starts , begins the noise and start another stream app crash .

Below the data of the test device :

Version library: 1.0.1
Android 6.0
Moto E with 4G LTE (2nd Gen)

What might be happening?

Attached an example of recorded audio output:
[stream.zip](https://github.com/wseemann/FFmpegMediaPlayer/files/294689/stream.zip)

**Comment by wseemann** [comment]
This is fixed in the [latest release](https://github.com/wseemann/FFmpegMediaPlayer/releases/tag/v1.0.2).

**Comment by w7virtual** [comment]
Great! The noise disappeared , but the failure continues to open another stream. See below the sequence:

V/FFmpegMediaPlayer-JNI: reset
V/FFmpegMediaPlayer-JNI: setDataSource: path http://example.stream.com:8000
V/FFmpegMediaPlayer-JNI: setAudioStreamType: 3
V/FFmpegMediaPlayer-JNI: getCurrentPosition: 0 (msec)
V/FFmpegMediaPlayer-JNI: getCurrentPosition: 0 (msec)
V/FFmpegMediaPlayer-JNI: getCurrentPosition: 0 (msec)
V/FFmpegMediaPlayer-JNI: getCurrentPosition: 0 (msec)
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9272e7b8 in tid 15294 (Thread-11318)

Remembering that this error also appears in the sample application "FMPDemo.apk" . If you open a stream and then try to open another, we see the same error.

**Comment by wseemann** [comment]
Fixed in version 1.0.3.
