### ISSUE TITLE
Have support for ffmpeg command line?  app playpath pageUrl swfUrl token

### ISSUE THREAD

**Issue by FloridaStream** [wseemann/FFmpegMediaPlayer#92]
FFmpegMediaPlayer have suport for ffmpeg command line same as vitamio? @wseemann

**Comment by wseemann** [comment]
Can you provide an example or point me to the documentation? I've not familiar with all of the capabilities of Vitamio.

**Comment by FloridaStream** [comment]
sample path command ```rtmp://0.0.0.0/live/ app=live playpath=channel20 token=whateversecure```
or ```http://samplesite.com/video.mp4``` ...

options.put("headers", "User-Agent: Mozilla/4.0 (compatible; MSIE 6.1; Windows XP) \r\n");
options.put("headers", "Cookie: acb=dsads\r\n");

I use this on vitamio to load normal links and ffmpeg links commands and ffmpeg AVOptions
```mVideoView.setVideoURI(Uri.parse(path), options);```

https://github.com/yixia/VitamioBundle/wiki/Use-FFmpeg-AVOption-in-Vitamio-4.1.0


I hope this helps you better understand what I said.

I use these custom ffmpeg parameters to run compounds links, but vitamio is unsupported, and wanted to migrate my project, I do not know if your can meet my needs.

The vitamio also use the isPlaying functions onComplete among other basic functions.
@wseemann

**Comment by wseemann** [comment]
@FloridaStream, I do support this, see the following method:

http://wseemann.github.io/FFmpegMediaPlayer/apidocs/index.html

**Comment by FloridaStream** [comment]
>  **I can play with `setDataSource("rtmp://0.0.0.0/live/ app=live playpath=channel20");` ?**

Using _ffmpeg_ command lines `app ` `playpath ` and othes? I need to know that, my application makes use of these _ffmpeg_ and other functions.

I intend to build with the `librtmp `in order to have more functions, such as `token=SecureToken`
I just want to be sure @wseemann 

sorry my english :anguished:

**Comment by wseemann** [comment]
Yes, you should be able to play that URL.
