### ISSUE TITLE
Why minSdkVersion is set to 21?

### ISSUE THREAD

**Issue by Nikitenko** [wseemann/FFmpegMediaPlayer#94]
def platform = "21"
minSdkVersion platform
https://github.com/wseemann/FFmpegMediaPlayer/blob/master/gradle/fmp-library/library/build.gradle

**Comment by IceJOKER** [comment]
@Nikitenko , wseemann commented - "The app uses OpenSLES for audio playback and NativeWindow for video playback, both require API 12+"
https://github.com/wseemann/FFmpegMediaPlayer/commit/dcb407d527a6296964df8fc909fc03735fc8e0fa

**Comment by Nikitenko** [comment]
@IceJOKER 
FFmpegMediaPlayer uses 21+, not 12+.
add dependency to build.gradle:

compile 'com.github.wseemann:FFmpegMediaPlayer:1.0.3'

and

Error:Execution failed for task ':androidappstore:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 **cannot be smaller than version 21 declared in library [com.github.wseemann:FFmpegMediaPlayer:1.0.3]** ...  	
Suggestion: use tools:overrideLibrary="wseemann.media.ffmpegmediaplayer" to force usage

It's OK, when I add to AndroidMainfest
<uses-sdk tools:overrideLibrary="wseemann.media.ffmpegmediaplayer"/>

But it seems like hack

**Comment by IceJOKER** [comment]
@Nikitenko oh, sorry, I didn't notice it. I'm using native MediaPlayer && ExoPlayer (first for old devices and second for others), it works nice also app size less than when I used this library(9MB vs. 22MB).

**Comment by HermanEldering** [comment]
The demo APK also has minimum sdk of 21. The player is not working (yet) in my app and I wanted to check that the demo did work on my device, but I cannot install it because my device has a lower Android version.

**Comment by kazemihabib** [comment]
why the minsdk is 21?

**Comment by nithi2023** [comment]
It is better to add Min SDK Version required in Repo home.

**Comment by wseemann** [comment]
This has been updated to API 12 and will be fixed in the next release.
