### ISSUE TITLE
Error while trying to play rtmp url

### ISSUE THREAD

**Issue by kadymuhammad** [wseemann/FFmpegMediaPlayer#95]
```
FFmpegMediaPlayer mp = new FFmpegMediaPlayer();
        mp.setOnPreparedListener(new FFmpegMediaPlayer.OnPreparedListener() {

            @Override
            public void onPrepared(FFmpegMediaPlayer mp) {
                mp.start();
            }
        });
        mp.setOnErrorListener(new FFmpegMediaPlayer.OnErrorListener() {

            @Override
            public boolean onError(FFmpegMediaPlayer mp, int what, int extra) {
                mp.release();
                return false;
            }
        });

        try {
            mp.setDataSource("rtmp://liveRadio.onlinehorizons.net/QuranKareem");
            mp.prepareAsync();
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        } catch (SecurityException e) {
            e.printStackTrace();
        } catch (IllegalStateException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
```

this code gives the flowing error : E/FFmpegMediaPlayer: Error (0,0)
And this is the log for FFmpegMediaPlayer 

```
V/FFmpegMediaPlayer-JNI: native_init
V/FFmpegMediaPlayer-JNI: native_setup
V/FFmpegMediaPlayer-JNI: setDataSource: path rtmp://liveRadio.onlinehorizons.net/QuranKareem
V/FFmpegMediaPlayer-JNI: notify: 100
E/FFmpegMediaPlayer: Error (0,0)
V/FFmpegMediaPlayer-JNI: release
```

Help please.

**Comment by FloridaStream** [comment]
try other rtmp link...

**Comment by vishnu888** [comment]
Any luck with this? I'm getting the same error when I try to play an rtsp link.

**Comment by kadymuhammad** [comment]
Nope

**Comment by wseemann** [comment]
`rtmp://liveRadio.onlinehorizons.net/QuranKareem` isn't a valid URL.

**Comment by rameshbo** [comment]
Hi,

I love FFmpeg Mediaplayer as i found this after days of search. 

I am too facing the issue mentioned in the thread...

I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1395)
D/PhoneWindowEx: [PWEx][generateLayout] setLGNavigationBarColor : colors=0xff000000
I/PhoneWindow: [setLGNavigationBarColor] color=0x ff000000
V/FFmpegMediaPlayer-JNI: native_init
V/FFmpegMediaPlayer-JNI: native_setup
V/FFmpegMediaPlayer-JNI: setDataSource: path rtmp://airlive.nic.in/livepkgr/airmarathi
D/libc: skt_base:0, kt_base:0, mptcp_enabled:0, socks_enabled:0, wifi_connected:1
D/libc: getaddrinfo called from pid =13793
D/libc: skt_base:0, kt_base:0, mptcp_enabled:0, socks_enabled:0, wifi_connected:1
D/libc: getaddrinfo called from pid =13793
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/PhoneWindow: notifyNavigationBarColor, color=0x: ff000000, token: android.view.ViewRootImplAO$WEx@f1c9767
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8909_LA.BR.1.2.6_RB1__release_AU (Idd51518bdf)
              OpenGL ES Shader Compiler Version: E031.29.00.00
              Build Date: 12/11/15 Fri
              Local Branch: 
              Remote Branch: quic/LA.BR.1.2.6_rb1.5
              Local Patches: NONE
              Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
V/RenderScript: 0xb923ecf8 Launching thread(s), CPUs 4
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c61a44e time:352862330
V/FFmpegMediaPlayer-JNI: notify: 100
E/FFmpegMediaPlayer: Error (0,0)
V/FFmpegMediaPlayer-JNI: release
V/ViewRootImpl: Contents drawing finished : com.xyz.abc/com.xyz.abc.MainActivity
Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'


and my rtmp is a valid url rtmp://airlive.nic.in/livepkgr/airmarathi. i tested it.

can you guide me on how to fix it.

**Comment by quhaoran007** [comment]
> rtmp://liveRadio.onlinehorizons.net/QuranKareem isn't a valid URL.

Hi @wseemann ,
What is a valid url? I have experienced the same thing. Thanks
